### ISSUE TITLE
not compiling for MSP 430f5529LP

### ISSUE THREAD

**Issue by shirish47** [rei-vilo/PervasiveDisplays_Library#1]
As on the link of pervasive display (http://www.pervasivedisplays.com/kits/ext2_kit) this controller should be supported how ever code does not compile I am trying to compile pervasiveDisplays_demo in pervasive display demo > examples .. 
there is a warning in the middle 
`WARNING: library PervasiveDisplays_Library claims to run on [msp432 architecture(s) and may be incompatible with your current board which runs on cc3200 architecture(s).
Generating function prototypes...`

and error at end .
`/var/folders/w2/jb9h2v3j5s5bs70q009xq2x00000gn/T/build4978595e0525fa9d390e8c550e874f0a.tmp/libraries/PervasiveDisplays_Library/Screen_EPD.cpp.o: In function `Screen_EPD::begin()':
/Users/shirishbytelens/Documents/Energia/libraries/PervasiveDisplays_Library/src/Screen_EPD.cpp:116: undefined reference to `operator new[](unsigned int)'
/Users/shirishbytelens/Documents/Energia/libraries/PervasiveDisplays_Library/src/Screen_EPD.cpp:117: undefined reference to `operator new[](unsigned int)'
collect2: ld returned 1 exit status`
exit status 1
Error compiling for board MSP-EXP430F5529LP.

**Comment by rei-vilo** [comment]
The `PervasiveDisplays_Library` does not support  MSP430 for the moment.

See [README.md](https://github.com/rei-vilo/PervasiveDisplays_Library/blob/master/README.md)

> It runs on the following boards with Energia: LaunchPad MSP432, LaunchPad CC3200, LaunchPad TM4C123G.

Don't confuse `Pervasive_EPD_BoosterPack2` and `PervasiveDisplays_Library`.

**Comment by shirish47** [comment]
Hi here is my comparison of what compiles what does not .. I am bit frustrated with this Paper .. I want to make a project that will display text but GFX required big RAM... https://docs.google.com/spreadsheets/d/1IHwUQKCwTqUh-dNvoXu55XYCcxcrQBPDtUeaAa9gsTI/edit?usp=sharing

**Comment by rei-vilo** [comment]
For CC3200 SPI issue, see https://github.com/energia/cc3200-core/issues/5.

**Comment by shirish47** [comment]
Ok that worked for CC3200.
