### ISSUE TITLE
Creating new fonts 

### ISSUE THREAD

**Issue by shirish47** [rei-vilo/PervasiveDisplays_Library#2]
GLCD  font Creator creates a  array of fonts but this library uses a 2D array of Fonts. I am using GLCD Font Creator. 

How do I get the 2D array of fonts? what I need to know to create new fonts?

**Comment by rei-vilo** [comment]
You can easily convert a 1D array into a 2D array.

For a professional usage, please check the [Licence](https://github.com/rei-vilo/PervasiveDisplays_Library#licence).
